export enum BOOKING_STATUS {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  MODIFIED = 'MODIFIED',
  CANCELLED_BY_USER = 'CANCELLED BY USER',
  CANCELLED_BY_KLEENIX = 'CANCELLED BY KLEENIX',
  NO_SHOW = 'NO SHOW',
  COMPLETED = 'COMPLETED',
  DELAYED = 'DELAYED',
}
