export enum BOOKING_STATUS {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  MODIFIED = 'MODIFIED',
  CANCELLED_BY_CUSTOMER = 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_KLEENIX = 'CANCELLED_BY_KLEENIX',
  NO_SHOW = 'NO_SHOW',
  COMPLETED = 'COMPLETED',
  DELAYED = 'DELAYED',
}
